services:
  - type: web
    name: rolmusic-frontend
    env: static
    rootDir: music-app
    buildCommand: NODE_OPTIONS=--max-old-space-size=4096 npm run build
    staticPublishPath: music-app/dist
    envVars:
      - key: NODE_OPTIONS
        value: --max-old-space-size=4096
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
